In [2]:
import numpy as np

In [7]:
arr1 = np.ones((3,4),str)
print(arr1)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [8]:
arr1 = np.ones((3,4),int)
print(arr1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
arr1 = np.ones((3,4),float)
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
arr1 = np.ones((3,4),bool)
print(arr1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


Creating An EMPTY Matrix

In [15]:
emptymatrix = np.empty((3,3))
print(emptymatrix)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.14617663e-321]
 [8.90104238e-307 1.24610383e-306 3.17320232e-317]]


In [16]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.14617663e-321],
       [8.90104238e-307, 1.24610383e-306, 3.17320232e-317]])

In [17]:
print(arr1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [18]:
print(arr1,int)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] <class 'int'>


In [19]:
arr2 = np.arange(1,13)

In [20]:
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
dff = arr2.reshape(2,3,2)
print(dff)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [27]:
dff2 = dff.ravel()
print(dff2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
