In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)  # values will be in between 0 and 1

array([0.92443713])

In [3]:
np.random.random((3,3))   # random matrix values are in b/w 0 and 1

array([[0.25358707, 0.5981834 , 0.94622062],
       [0.7672639 , 0.02901868, 0.37716714],
       [0.51060704, 0.63308122, 0.20051489]])

In [4]:
np.random.randint(1,4)    #random single integer value

1

In [11]:
np.random.randint(1,4,(3,4))   # random matrix with integer values

array([[2, 3, 3, 1],
       [1, 3, 1, 2],
       [3, 1, 3, 1]])

In [10]:
np.random.randint(1,4,(2,3,4))   #Output 1

array([[[3, 2, 1, 1],
        [3, 2, 3, 2],
        [2, 2, 2, 3]],

       [[2, 1, 3, 3],
        [3, 2, 1, 2],
        [2, 1, 3, 2]]])

In [7]:
np.random.randint(1,4,(2,3,4))  #Output 2  >> for same command output 1 and 2 are different. 

array([[[3, 1, 3, 3],
        [1, 2, 2, 1],
        [3, 2, 2, 1]],

       [[3, 3, 1, 2],
        [3, 1, 1, 1],
        [1, 3, 3, 2]]])

So if we want all the values same again and again in the matrix we use the below function :: seed() 

In [13]:
np.random.seed(12)    #seed input can be from 0 to 2**32 -1
np.random.randint(1,4,(2,3,4))      #Output - A 

array([[[3, 2, 2, 3],
        [1, 1, 3, 2],
        [1, 2, 2, 2]],

       [[3, 3, 3, 1],
        [2, 1, 1, 2],
        [3, 2, 3, 1]]])

In [12]:
np.random.seed(12)
np.random.randint(1,4,(2,3,4))         #Output - A  >> both output are same

array([[[3, 2, 2, 3],
        [1, 1, 3, 2],
        [1, 2, 2, 2]],

       [[3, 3, 3, 1],
        [2, 1, 1, 2],
        [3, 2, 3, 1]]])

In [14]:
np.random.rand(3)

array([0.52122603, 0.55203763, 0.48537741])

In [15]:
np.random.rand(3,3)

array([[0.76813415, 0.16071675, 0.76456045],
       [0.0208098 , 0.13521018, 0.11627302],
       [0.30989758, 0.67145265, 0.47122978]])

In [18]:
np.random.randn(3,3)

array([[-0.58108011,  0.87313484,  0.91056528],
       [ 1.04764561, -1.18963857, -1.24056205],
       [ 0.05530221,  0.21221081, -0.34532435]])

In [19]:
x = [1,2,3,4]
np.random.choice(x)

3

In [20]:
x = [1,2,3,4]
np.random.choice(x)

3

In [21]:
x = [1,2,3,4]
np.random.choice(x)

3

In [22]:
for i in range(20):
    print(np.random.choice(x))

2
4
3
1
3
3
4
1
4
2
3
4
1
4
2
2
1
2
2
2


In [23]:
x

[1, 2, 3, 4]

In [24]:
np.random.permutation(x)

array([1, 3, 2, 4])

In [25]:
np.random.permutation(x)

array([4, 2, 3, 1])

In [32]:
for i in range(20):
    print(np.random.permutation(x))

[4 3 1 2]
[4 2 1 3]
[3 4 1 2]
[3 4 1 2]
[1 4 2 3]
[4 1 3 2]
[1 3 4 2]
[2 1 3 4]
[3 1 2 4]
[4 3 1 2]
[2 3 1 4]
[1 4 2 3]
[1 3 2 4]
[1 3 2 4]
[3 4 2 1]
[1 2 4 3]
[3 1 2 4]
[2 4 1 3]
[1 3 4 2]
[4 3 2 1]
